spring:
  application:
    name: auth-service

config:
  ldap:
    user-search-filter: (mail={0})
    user-search-base: ou=Users,dc=ieslavereda,dc=local
    group-search-filter: memberUid={0}
    group-search-base: ou=Groups,dc=ieslavereda,dc=local
    url: ldap://localhost:389
    admin-user: cn=admin,dc=ieslavereda,dc=local
    admin-pass: 12345678
  privateKey: ZnJhc2VzbGFyZ2FzcGFyYWNvbG9jYXJjb21vY2xhdmVlbnVucHJvamVjdG9kZWVtZXBsb3BhcmFqd3Rjb25zcHJpbmdzZWN1cml0eQ==bWlwcnVlYmFkZWVqbXBsb3BhcmFiYXNlNjQ=

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true