openapi: 3.0.0
info:
  title: AuthServices IES La Vereda
  version: 1.0.0
tags:
  - name: Login Actions
    description: Operation related with login
paths:
  /auth/login:
    post:
      summary: Login
      description: Login with LDAP service
      operationId: login
      tags:
        - Login Actions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
components:
  schemas:
    LoginRequest:
      type: object
      description: Login request
      properties:
        username:
          type: string
          format: email
          description: email with login
        password:
          type: string
          description: password with login
    LoginResponse:
      type: object
      description: Login request
      properties:
        user:
          $ref: '#/components/schemas/User'
        token:
          type: string
    User:
      type: object
      description: User information
      properties:
        email:
          type: string
          description: Email of teacher
        roles:
          type: array
          description: Role's list of teacher
          items:
            type: string
    ErrorType:
      type: object
      description: Error response
      properties:
        code:
          type: integer
          description: Error code
        description:
          type: string
          description: Error description
      required:
        - code
        - description
      example:
        code: 400
        description: "Bad Request"